upstream apache_backends {
    # El bloque 'upstream' define un grupo de servidores backend.
    # Por defecto, Nginx usa el algoritmo Round Robin para balancear.
    # Esto significa que alternará las peticiones 1 a 1 entre ambos.
    server web_lautaro_1:80;
    server web_lautaro_2:80;
}

server {
    # Escucha en el puerto 80 del contenedor Nginx
    listen 80;
    server_name localhost;

    # Se inyectan estas cabeceras HTTP hacia los Apache 
    # para que ellos sepan de dónde vino la petición original
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    location / {
        # 'proxy_pass' envía el tráfico entrante al grupo definido arriba
        proxy_pass http://apache_backends;

        # Desactivamos el cache proxy para poder probar el balanceo.
        # Si hubiera caché, Nginx podría devolver la misma respuesta 
        # guardada en memoria sin consultar a los Apaches.
        proxy_no_cache 1;
        proxy_cache_bypass 1;
        
        # Estas cabeceras mágicas se devuelven hacia el navegador del cliente.
        # Gracias a 'X-Upstream' nuestro JavaScript sabe qué IP interna respondió.
        add_header X-Upstream $upstream_addr always;
        add_header X-Balancer "Alta_Disponibilidad_Lautaro" always;
    }

    # Endpoint de estado para que Docker compruebe que Nginx está vivo (healthcheck)
    location /nginx-health {
        access_log off;
        return 200 "Nginx OK\n";
        add_header Content-Type text/plain;
    }
}
