map $upstream_addr $servidor_id_lautaro {
    "~172\.18\.0\.3" "Servidor_Web_Alfa_ASIX"; # web_lautaro_1
    "~172\.18\.0\.2" "Servidor_Web_Beta_ASIX";  # web_lautaro_2
    default          "Balanceador_Nginx_Lautaro";
}

upstream apache_backends {
    random; # Forzamos selección aleatoria para que el cambio sea visible en F5
    server web_lautaro_1:80;
    server web_lautaro_2:80;
}

server {
    # Escucha en el puerto 80 del contenedor Nginx
    listen 80;
    server_name localhost;
    server_tokens off;

    # Se inyectan estas cabeceras HTTP hacia los Apache 
    # para que ellos sepan de dónde vino la petición original
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    location / {
        # 'proxy_pass' envía el tráfico entrante al grupo definido arriba
        proxy_pass http://apache_backends;
        proxy_http_version 1.1;
        proxy_set_header Connection "close";

        # Desactivamos el cache proxy para poder probar el balanceo.
        proxy_no_cache 1;
        proxy_cache_bypass 1;
        
        # --- PERSONALIZACIÓN TÉCNICA F12 ---
        # Ocultamos la cabecera original para que no aparezca duplicada o genérica
        proxy_hide_header Server;
        
        # Añadimos la cabecera Server con el nombre dinámico calculado en el map
        add_header Server $servidor_id_lautaro always;
        
        # Cabeceras adicionales para depuración
        add_header X-Upstream $upstream_addr always;
        add_header X-Balancer "Alta_Disponibilidad_Lautaro" always;
    }

    # Endpoint de estado para que Docker compruebe que Nginx está vivo (healthcheck)
    location /nginx-health {
        access_log off;
        return 200 "Nginx OK\n";
        add_header Content-Type text/plain;
    }
}
